steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/capturecare:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/capturecare:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/capturecare'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'capturecare'
      - '--image'
      - 'gcr.io/$PROJECT_ID/capturecare:$SHORT_SHA'
      - '--region'
      - 'australia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'USE_SECRET_MANAGER=true,GCP_PROJECT_ID=$PROJECT_ID,USE_CLOUD_STORAGE=true,GCS_BUCKET_NAME=capturecare-v7-storage'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:australia-southeast2:capturecare-db'
      - '--set-secrets'
      - 'DATABASE_URL=capturecare-db-connection:latest'
timeout: 1200s
